/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef RankingService_CONSTANTS_H
#define RankingService_CONSTANTS_H

#include "RankingService_types.h"

namespace ranking {

class RankingServiceConstants {
 public:
  RankingServiceConstants();

};

extern const RankingServiceConstants g_RankingService_constants;

} // namespace

#endif
