/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "RankingService_constants.h"

namespace ranking {

const RankingServiceConstants g_RankingService_constants;

RankingServiceConstants::RankingServiceConstants() {
}

} // namespace

